- HISTORY.rst
- README.rst
- test_tox_travis.py
- tox.ini
- tox_travis.py
It would be most convenient if the default setup automatically ran all of the environments that match a particular version of Python. For instance, if we had the following `tox.ini`:
```ini
[tox]
envlist = py27-{django,flask,pyramid}, docs
```
In this case, we'd like the `py27-django`, `py27-flask`, and `py27-pyramid` envs to be run automatically, without additional configuration, though the `docs` env would be left out of the run in the default settings.
The right approach for this seemed to be to interpret the factors (the parts separated with `-`), and match accordingly. This extensible approach should make it easy to override as well, as just adding this new section to the `tox.ini` should be sufficient to get the docs running, and doesn't cause a whole bunch of duplication:
```ini …
```
> Match environments based on factors

- .travis.yml
- tox.ini
The latest version of pip, version 8, does not support Python 3.2 any longer. This has manifested itself in failing builds on Travis CI. Since pip has decided it's reasonable to drop support for Python 3.2, it probably is for tox-travis as well.
PyPy3 still only support Python 3.2, so it is also dropped for now.
> Drop support for Python 3.2

- .gitignore
- test_tox_travis.py
- tox.ini
- tox_travis.py
For instance, ``coveralls`` in the ``[tox:travis]`` section would get ignored because ``py34`` matches things in the envlist already.
```
[tox]
envlist = py34, py34-docs, py34-django
[tox:travis]
3.4 = py34, coveralls
[testenv:coveralls]
basepython=python3.4
```
If you can think of a better oneliner to explain it, more power to you :-)
> Fix desired envs not matching declared envs that aren't in the envlist

- .travis.yml
- HISTORY.rst
- test_tox_travis.py
- tox_travis.py
Fixes #9
Closes #10
The improved error handling of #10 should not be needed with this approach, and any new python version should "just work", assuming that the generation of tox envs continues following the current pattern.
> Generate default env instead of hard-coded lookup

- test_tox_travis.py
- tox_travis.py
Using sys.version_info is a good fallback, but it doesn't allow TRAVIS_PYTHON_VERSION to be set explicitly in scenarios where Travis doesn't deal with Python versions, such as on multi-os builds under osx instead of linux.
Recent comments on #4 suggest support for multi-os builds, but that support is very limited currently. This should allow manually set ``TRAVIS_PYTHON_VERSION`` to behave identically to using the ``python`` configuration for versions.
References #4
> Parse TRAVIS_PYTHON_VERSION to get python version

- .travis.yml
- setup.py
- src/tox_travis.py
- tox.ini
PyPy has started releasing alpha releases of PyPy3 v5.2,
and Travis now supports `python: pypy3.3-5.2-alpha1`.
PyPy3 v5.2 depends on virtualenv>=15.0.2, whereas Travis installs 12.0.6.
Only force the use of virtualenv>=15.0.2 on PyPy3 v5.2, so that existing
users of tox-travis are not impacted.
This is complicated by Travis providing setuptools 12.0.5,
which does not support `platform_python_implementation=="PyPy"`
as an environment marker.  Prior to setuptools 20.10.0 there is patchy
support for environment markers, and setup.py fails while parsing them.
To avoid breakage if someone is installing tox-travis using an older
setuptools, setup.py patches _markerlib and pkg_resources to do the
correct environment marker matching.
However the typical Travis-CI usage is via `pip install …
> Support PyPy3 v5.2 with setuptools hackery

- .travis.yml
- setup.py
pytest 3.0 included Python syntax only available on Python 3.3
Also update Travis 'nightly' to be '3.6-dev',
as nightly is now Python 3.7 which isnt supported
by the latest released version of tox.
Fixes #31
Fixes #32
> Python 3.2 requires pytest<3

- HISTORY.rst
- README.rst
- src/tox_travis.py
- tests/test_helpers.py
- tests/test_tox_travis.py
Add support for `os`, `language`, and `python` Travis factors, as well as for environment factors as well.
This includes, supercedes, and ultimately fixes #34. Fixes #4, Fixes #25, and references #19.
> Support alternative Travis factors

- .travis.yml
- README.rst
- tox.ini
The docs env builds the docs with sphinx. The desc env builds ensures that the long description that will be given to PyPI is valid reStructuredText. That would have avoided my issues today, where I had simply forgotten to lengthen the title of one of the sections in the HISTORY file.
> Add tox envs for docs and desc

- docs/toxenv.rst
According to https://docs.travis-ci.com/user/customizing-the-build, there's no `include`, just `matrix.include`.
> Fix example .travis.yml

- src/tox_travis/after.py
- tests/test_after.py
> Exit gracefully in after-all for external pull requests

- .travis.yml
- docs/after.rst
It's better suited to the project Travis configuration in the web UI anyway.
https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
> Remove GITHUB_TOKEN from .travis.yml

- .travis.yml
- src/tox_travis/toxenv.py
> Allow PyPy3 support to work with PyPy3 5.5

- setup.py
`iter(dict)` is equivalent to `iter(dict)`. Can drop the unnecessary `keys()` call.
> Remove unnecessary keys()

- docs/after.rst
- src/tox_travis/after.py
- src/tox_travis/hooks.py
- src/tox_travis/toxenv.py
- tests/test_after.py
- tests/test_toxenv.py
The tox_configure hook is much better suited for the purpose of toxenv. This PR is some refactors to aid, and a move of the bulk of the project to being triggered via the tox_configure hook. This is based off of the idea of #61, so it also closes #71. Thanks @rpkilby!
The abandonment of `TOXENV` to communicate with Tox also means that this also fixes #44 as a side-effect.
> Move toxenv to tox_configure hook

- src/tox_travis/after.py
- src/tox_travis/toxenv.py
- tests/test_after.py
- tests/test_toxenv.py
If successful, this fixes #57.
No new tests have been added, though some have been modified to adjust to the new call signature.
> Use the same config file as Tox

- src/tox_travis/after.py
- src/tox_travis/hacks.py
- src/tox_travis/hooks.py
- tests/test_after.py
- tests/test_hacks.py
- tests/test_hooks.py
Refactor the monkeypatching required by after to allow it to look more like a hook. This will hopefully make the implementation a bit easier to follow and test, since the hook is unconditionally monkeypatched in.
> Refactor after monkeypatch

- .gitignore
- .travis.yml
The only gotcha I can think of for this is if somehow it's running on a really old version of pip. But I think that should be a non-issue on Travis. If it is an issue, I would expect us to have already seen it, since we are installing wheels in every job anyway.
> Deploy only a wheel to PyPI

- .travis.yml
- HISTORY.rst
Ideally I want to fix the deployment so that we no longer ship an egg. Perhaps even not ship any more sdists either, so that we can drop the sdist tests from the build as well.
> Draft 0.9 release notes

- .travis.yml
- HISTORY.rst
- docs/after.rst
- src/tox_travis/hooks.py
- tests/test_after.py
- tests/test_envlist.py
- tox.ini
Deprecate the After All feature in favor of Travis native build stages. Because they are native to Travis, stages are a better way to implement waiting for all the jobs to finish.
Add a deprecation warning on usage, in the changelog, and in the docs.
Use build stages in our own deployment process, and use the new conditional builds, stages, and jobs to limit when the deployment happens, and which branches are built, and to better signal that only tags should be deployed.
If merged, this will:
* Fix #69
* Close #42 as `wontfix`
* Close #43 as `wontfix`
----
@rpkilby : I know that the past couple of days have been a flurry of pull requests that I've merged without your review. They were all related to deployment, so I didn't want to hold up the release for them. This one is different, and …
> Deprecate After All

- .travis.yml
Since the deploy stage already ensures that it's a tag running, it's redundant to have it on the deploy itself.
> Skip tag check on deploy

- .appveyor.yml
- .gitignore
- .travis.yml
- docs/contributing.rst
- setup.py
- tests/test_envlist.py
- tox.ini
Tox upstream has completely dropped support for Python 3.2 and 3.3, thus Tox-Travis now does as well.
> Drop support for Python 3.2 and 3.3

- README.rst
tox is all lower case. Always. Everywhere.
Plugin names are also just lower case.
Thanks for tolerating my tox lower case obsession :)
> fix tox casing

- .travis.yml
- HISTORY.rst
- docs/contributing.rst
- setup.py
- tox.ini
Replaces 3.7-dev travis environment with release 3.7.
And uses standard two space indents throughout .travis.yml
Closes https://github.com/tox-dev/tox-travis/issues/124
> Add Python 3.7 support in trove classifiers

- docs/after.rst
- docs/contributing.rst
- docs/envlist.rst
- setup.py
- src/tox_travis/hacks.py
- tests/test_after.py
* Remove `sudo: false` from examples, it's no longer needed: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
* Fix typos
* Update repo org name
> Docs: Remove sudo from examples, fix typos, update org name

- .travis.yml
- docs/after.rst
- docs/contributing.rst
- setup.py
- tests/test_envlist.py
- tox.ini
Python 2.6 is failing the build ([example](https://github.com/tox-dev/tox-travis/pull/138)). It's EOL and no longer receiving security updates (or any updates) from the core Python team.
Version | Release date | Supported until
--- | ---------- | ----------
2.6 | 2008-10-01 | 2013-10-29
2.7 | 2010-07-03 | 2020-01-01
3.0 | 2008-12-03 | 2009-06-27
3.1 | 2009-06-27 | 2012-04-09
3.2 | 2011-02-20 | 2016-02-27
3.3 | 2012-09-29 | 2017-09-29
3.4 | 2014-03-16 | 2019-03-16
Source: https://en.wikipedia.org/wiki/CPython#Version_history
It's also little used. Here's the pip installs for tox-travis from PyPI for August 2019:
| category | percent | downloads |
|----------|--------:|----------:|
| 3.6      |  34.85% |    40,979 |
| 3.7      |  20.44% |    24,028 |
| 2.7      |  18.72% |    22,012 |
| 3.5 …
> Drop support for EOL Python 2.6

- README.rst
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
I missed this in https://github.com/tox-dev/tox-travis/pull/135.
> README: sudo no longer needed

- .appveyor.yml
- README.rst
- docs/envlist.rst
- tests/test_envlist.py
- tox.ini
As Python 3.4 is end of life since 2019-03-18
https://www.python.org/downloads/release/python-3410/
Remove compat :
- update setup.py
- update docs
- update tox / travis / appveyor
- update tests with real examples
> Update tests and docs

- .travis.yml
It is deprecated:
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> Do not use `sudo: true` any more
